
####################################################
#Signup request#####################################
####################################################
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
"name_surname":"taaeqs22dfs sdfsdfst",
"email":"teaaasaat@efe.fr",
"password":"te3445st"}

## zer@zer.fr Ab234ZxW

####################################################
#Login request######################################
####################################################
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
"email":"Deuxieme@gmail.com",
"password":"Ab234ZxW" }


#####################################################
# Create a new post with valid authorization header.#
#####################################################
POST http://localhost:5000/api/post/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="body"

Ceci est un premier post.Ceci est un premier post.Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.
Ceci est un premier post.

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="FZ_v4BoXoAAesvy.jpg"
Content-Type: image/jpg

< ./FZ_v4BoXoAAesvy.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#####################################################
# Display all posts with valid authorization header.#
#####################################################
GET http://localhost:5000/api/post/
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

###########################################################
# Display a specific post with valid authorization header.#
###########################################################
GET http://localhost:5000/api/post/195
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

###########################################################
# Modify a specific post with valid authorization header.##
###########################################################
PUT http://localhost:5000/api/post/195
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="body"

Voici un post de test modifié.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="FaCK_29WIAIvRG6.jpg"
Content-Type: image/jpg

< ./FaCK_29WIAIvRG6.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###########################################################
# Delete a specific post with valid authorization header.##
###########################################################
DELETE http://localhost:5000/api/post/195
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw


#############################################################################################
#############################################################################################
#COMMENTS
#############################################################################################
#############################################################################################

###########################################################
# GET ALL COMMENTS NO MATTER THE POST ID WITH VALID AUTH.##
###########################################################
GET http://localhost:5000/api/post/getEverycomments
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

##################################################################
# CREATE a NEW COMMENT ON A POST with valid authorization header.#
##################################################################
POST http://localhost:5000/api/post/195/comments
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

{
"body":"Commentaire direct"
}

#############################################################
# ANSWER a specific COMMENT with valid authorization header.#
#############################################################
POST http://localhost:5000/api/post/195/comments/252
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

{
"body":"Réponse à un commentaire"
}

###################################################################
# DISPLAY EVERY COMMENT ON A POST with valid authorization header.#
###################################################################
# # Send page and limit in the request parameters.
GET http://localhost:5000/api/post/172/comments
Content-Type: application/json

Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

###################################################################
# GET http://localhost:5000/api/post/172/comments
# Content-Type: application/json

# Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw


################################################################
# DISPLAY ANSWERS TO A COMMENT with valid authorization header.#
################################################################
GET http://localhost:5000/api/post/172/comments/116
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

#############################################################
# MODIFY a specific comment with valid authorization header.#
#############################################################
PUT http://localhost:5000/api/post/127/comments/80
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw

{
    "body":"Voici un commentaire de test modifié."
}
#############################################################
# DELETE a specific comment with valid authorization header.#
#############################################################
DELETE http://localhost:5000/api/post/127/comments/80
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw


#############################################################################################
#############################################################################################
#LIKES
#############################################################################################
#############################################################################################


############################################################
# Like or dislike a specific post with valid authorization.#
############################################################
POST http://localhost:5000/api/post/206/like
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTY2NDQ2NzgxMywiZXhwIjoxNjY0NTU0MjEzfQ.YdNsvftP7A3JIlYk7PqsJiyjSip8P1t5l126b7sm4Yw
#It will be done by sending a user id and an array containing either 1, 0 or -1 for like, unlike or dislike.#

{
"like": -1,
"voter_id": 9
}
